            "sharing": {
                "all": ["facebook","discord", "google", "twitter", "weibo", "instapaper", "github", "telegram"],
                "facebook": false,
                "discord": true,
                "discord_link": "https://discord.com/channels/701556293575639040/701556293575639043",
                "google": false,
                "github": true,
                "github_link": "https://github.com/DECENTRALIZEDCLIMATE",
                "telegram": true,
                "telegram_link": "https://t.me/decentralizedclimate",
                "instapaper": false,
                "twitter": true,
                "twitter_link": "https://twitter.com/dc_foundation",
                "vk": false,
                "weibo": false
            },
